name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'examples/cv.pdf'
        destination_repo: 'manueldiagostino/manueldiagostino.github.io'
        destination_folder: 'files'
        user_email: 'diagostinomanuel@gmail.com'
        user_name: 'manueldiagostino'
        commit_message: 'Automatic update of files/cv.pdf'
        destination_branch: 'master'
